In [3]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from datetime import date
from sklearn.model_selection import train_test_split

Import the raw data set into a Pandas DataFrame. Perform some exploratory analysis on the raw data set. Check for the types of data hygiene issues mentioned in the lesson. Whenever you find a possible issue, write some code to fix it. Apply your fixes systematically, not case-by-case. Be sure to include comments to explain your process.

In [4]:
songs = pd.read_csv('ml-03-data-processing-songs-dataset.csv')
songs.head()

,Index,Title,Artist,Top Genre,Year,Month,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004.0,10,157.0,30.0,53.0,-14.0,11.0,68.0,201,94.0,3.0,71.0
1,2,Black Night,Deep Purple,album rock,2000.0,3,135.0,79.0,50.0,-11.0,17.0,81.0,207,17.0,7.0,39.0
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001.0,6,168.0,69.0,66.0,-9.0,7.0,52.0,341,2.0,17.0,69.0
3,4,The Pretender,Foo Fighters,alternative metal,2007.0,1,173.0,96.0,43.0,-4.0,3.0,37.0,269,0.0,4.0,76.0
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002.0,8,106.0,82.0,58.0,-5.0,10.0,87.0,256,1.0,3.0,59.0

In [5]:
songs['Length (Duration)']=songs['Length (Duration)'].apply(lambda x: str(x))
songs['Length (Duration)'] = songs['Length (Duration)'].apply(lambda x: x.replace(',',''))

songs['Length (Duration)'] = songs['Length (Duration)'].astype(float)

Seeing if all the months are Correctly formatted

In [6]:
songs.Month.unique()

array(['10', '3', '6', '1', '8', '2', '9', '12', '11', '4', '7', '5',
       'Jan', 'Dec', 'Sep', 'Apr', 'Jun', 'May'], dtype=object)

In [7]:
for i in range(len(songs)):
    if songs.Month.iloc[i] == 'Jan':
        songs.at[i,'Month'] = '1'
    elif songs.Month.iloc[i] == 'Dec':
        songs.at[i,'Month'] = '12'
    elif songs.Month.iloc[i] == 'Sep':
        songs.at[i,'Month'] = '9'
    elif songs.Month[i] == 'Apr':
        songs.at[i,'Month'] = '4'
    elif songs.Month[i] == 'Jun':
        songs.at[i,'Month'] = '6'
    elif songs.Month[i] == 'May':
        songs.at[i,'Month'] = '5'

songs.Month.unique()

array(['10', '3', '6', '1', '8', '2', '9', '12', '11', '4', '7', '5'],
      dtype=object)

In [8]:
#Doing some other EDA
songs.describe()

,Index,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
count,1994.000000,1987.000000,1985.000000,1986.000000,970.000000,1987.000000,1986.000000,960.000000,1985.000000,1986.000000,1990.000000,1987.000000
mean,997.500000,1959.526422,120.230730,59.664149,52.983505,-9.009562,19.013092,50.820833,262.612594,28.897281,4.989950,59.518873
std,575.762538,250.650856,28.625839,22.159565,15.426169,3.652092,16.739697,24.955125,93.749643,29.020822,4.402899,14.362661
min,1.000000,92.000000,15.000000,3.000000,10.000000,-27.000000,2.000000,5.000000,93.000000,0.000000,2.000000,11.000000
25%,499.250000,1978.000000,99.000000,42.000000,42.000000,-11.000000,9.000000,30.000000,212.000000,3.000000,3.000000,49.000000
50%,997.500000,1993.000000,119.000000,61.000000,53.000000,-8.000000,12.000000,49.000000,245.000000,18.000000,4.000000,62.000000
75%,1495.750000,2007.000000,136.000000,78.000000,64.000000,-6.000000,23.000000,71.000000,290.000000,50.000000,5.000000,71.000000
max,1994.000000,2019.000000,305.000000,100.000000,96.000000,-2.000000,99.000000,98.000000,1412.000000,99.000000,55.000000,100.000000

It looks like the Year category with 92 might be a mistype (should be 1992)

In [9]:
for i in range(len(songs)):
    if songs['Year'].iloc[i]==92:
        songs.at[i,'Year'] = 1992

Find the number of missing values in each column and each row. Remove rows where at least 50% of the values are missing. Then remove columns where at least 50% of the values are missing.

In [10]:
for column in songs.columns:
    #print(column, songs[column].isna().sum(),len(songs)/2)
    num_null  = songs[column].isna().sum()

    if num_null > (len(songs)/2):
        songs = songs.drop(columns=[column])

songs.columns

Index(['Index', 'Title', 'Artist', 'Top Genre', 'Year', 'Month',
       'Beats Per Minute (BPM)', 'Energy', 'Loudness (dB)', 'Liveness',
       'Length (Duration)', 'Acousticness', 'Speechiness', 'Popularity'],
      dtype='object')

In [11]:
len(songs)

1994

In [31]:
num_cols = len(songs.columns)

for i in range(len(songs)):
    #print(column, songs[column].isna().sum(),len(songs)/2)
    num_null  = songs.iloc[i].isna().sum()
    #print(num_null)
    if num_null >= num_cols/2:
        print(f'index{i},{num_null}')

#it looks like after dropping the columns, there are no rows with more than 50% of null rows

Calculate descriptive statistics for each column. Let's define an outlier as a value at least 3 standard deviations away from the mean. Which columns have outliers? What are those values?

In [13]:
songs.describe()

,Index,Year,Beats Per Minute (BPM),Energy,Loudness (dB),Liveness,Length (Duration),Acousticness,Speechiness,Popularity
count,1994.000000,1987.000000,1985.000000,1986.000000,1987.000000,1986.000000,1985.000000,1986.000000,1990.000000,1987.000000
mean,997.500000,1992.993961,120.230730,59.664149,-9.009562,19.013092,262.612594,28.897281,4.989950,59.518873
std,575.762538,16.111644,28.625839,22.159565,3.652092,16.739697,93.749643,29.020822,4.402899,14.362661
min,1.000000,1956.000000,15.000000,3.000000,-27.000000,2.000000,93.000000,0.000000,2.000000,11.000000
25%,499.250000,1979.000000,99.000000,42.000000,-11.000000,9.000000,212.000000,3.000000,3.000000,49.000000
50%,997.500000,1993.000000,119.000000,61.000000,-8.000000,12.000000,245.000000,18.000000,4.000000,62.000000
75%,1495.750000,2007.000000,136.000000,78.000000,-6.000000,23.000000,290.000000,50.000000,5.000000,71.000000
max,1994.000000,2019.000000,305.000000,100.000000,-2.000000,99.000000,1412.000000,99.000000,55.000000,100.000000

In [14]:
def get_outliers(column):
    three_sd = 3*(songs[column].std())
    mean = songs[column].sum()/len(songs)
    max = mean + three_sd
    min = mean - three_sd
    vals = []
    for i in range(len(songs)):
        val = songs[column].iloc[i]
        if val > max:
            vals.append(val)
            #songs.at[i,column] = max
        elif val < min:
            vals.append(val)
            #songs.at[i,column] = min
    print(column, vals)

In [15]:
for column in songs.describe().columns:
    get_outliers(column)

Index []
Year []
Beats Per Minute (BPM) [18.0, 305.0, 206.0, 15.0, 297.0]
Energy []
Loudness (dB) [-21.0, -20.0, -22.0, -22.0, -20.0, -20.0, -24.0, -20.0, -21.0, -22.0, -24.0, -27.0, -21.0, -21.0, -22.0, -21.0, -21.0, -20.0, -21.0, -22.0, -22.0, -21.0]
Liveness [81.0, 70.0, 93.0, 79.0, 70.0, 97.0, 70.0, 83.0, 72.0, 97.0, 97.0, 87.0, 96.0, 71.0, 99.0, 92.0, 78.0, 95.0, 71.0, 90.0, 81.0, 95.0, 87.0, 91.0, 85.0, 89.0, 76.0, 73.0, 72.0, 85.0, 73.0, 86.0, 76.0, 73.0, 82.0, 77.0, 97.0, 85.0, 99.0, 78.0, 98.0, 96.0, 93.0, 85.0, 94.0, 77.0, 91.0, 96.0, 84.0, 97.0, 76.0, 73.0, 92.0, 80.0, 76.0, 83.0, 76.0]
Length (Duration) [639.0, 629.0, 602.0, 809.0, 598.0, 598.0, 671.0, 620.0, 663.0, 1412.0, 581.0, 1121.0, 559.0, 575.0, 1367.0, 811.0, 576.0, 715.0, 653.0, 590.0, 966.0, 859.0, 659.0, 564.0, 703.0, 1292.0]
Acousticness []
Speechiness [25.0, 26.0, 30.0, 23.0, 24.0, 19.0, 24.0, 20.0, 39.0, 23.0, 20.0, 19.0, 32.0, 19.0, 24.0, 44.0, 30.0, 24.0, 25.0, 31.0, 20.0, 46.0, 38.0, 55.0, 22.0, 23.0, 32.0, 36.0, 19.0, 31.0, 26.0, 28.0, 30.0, 20.0, 30.0, 29.0, 31.0, 19.0, 27.0, 32.0, 39.0, 41.0]
Popularity [16.0, 14.0, 15.0, 13.0, 16.0, 16.0, 15.0, 12.0, 11.0]

With the remaining columns, use scikit-learn to impute missing values. For continuous features, fill in the mean. For categorical features, fill in the mode.

In [16]:
songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   1994 non-null   int64
 1   Title                   1991 non-null   object
 2   Artist                  1986 non-null   object
 3   Top Genre               1986 non-null   object
 4   Year                    1987 non-null   float64
 5   Month                   1994 non-null   object
 6   Beats Per Minute (BPM)  1985 non-null   float64
 7   Energy                  1986 non-null   float64
 8   Loudness (dB)           1987 non-null   float64
 9   Liveness                1986 non-null   float64
 10  Length (Duration)       1985 non-null   float64
 11  Acousticness            1986 non-null   float64
 12  Speechiness             1990 non-null   float64
 13  Popularity              1987 non-null   float64
dtypes: float64(9), int64(1), object(4)
memory usage: 218.2+ KB

In [17]:
imp_mean = SimpleImputer(missing_values= np.nan, strategy='mean')
num_cols=['Beats Per Minute (BPM)','Energy','Loudness (dB)','Liveness','Length (Duration)','Acousticness','Popularity','Speechiness']
for col in num_cols:
    songs[col]=imp_mean.fit_transform(songs[[col]])

songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   1994 non-null   int64
 1   Title                   1991 non-null   object
 2   Artist                  1986 non-null   object
 3   Top Genre               1986 non-null   object
 4   Year                    1987 non-null   float64
 5   Month                   1994 non-null   object
 6   Beats Per Minute (BPM)  1994 non-null   float64
 7   Energy                  1994 non-null   float64
 8   Loudness (dB)           1994 non-null   float64
 9   Liveness                1994 non-null   float64
 10  Length (Duration)       1994 non-null   float64
 11  Acousticness            1994 non-null   float64
 12  Speechiness             1994 non-null   float64
 13  Popularity              1994 non-null   float64
dtypes: float64(9), int64(1), object(4)
memory usage: 218.2+ KB

In [18]:
imp_mode = SimpleImputer(missing_values= np.nan, strategy='most_frequent')
cat_cols=['Title','Artist','Top Genre','Year','Month']
for col in cat_cols:
    new_col = imp_mode.fit_transform(songs[[col]])
    songs[col]=new_col
songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   1994 non-null   int64
 1   Title                   1994 non-null   object
 2   Artist                  1994 non-null   object
 3   Top Genre               1994 non-null   object
 4   Year                    1994 non-null   float64
 5   Month                   1994 non-null   object
 6   Beats Per Minute (BPM)  1994 non-null   float64
 7   Energy                  1994 non-null   float64
 8   Loudness (dB)           1994 non-null   float64
 9   Liveness                1994 non-null   float64
 10  Length (Duration)       1994 non-null   float64
 11  Acousticness            1994 non-null   float64
 12  Speechiness             1994 non-null   float64
 13  Popularity              1994 non-null   float64
dtypes: float64(9), int64(1), object(4)
memory usage: 218.2+ KB

Combine the date-related columns into one column with the Pandas to_datetime() method, then use that column to create a numeric Age column (in years). Calculate Age based on today's date; it doesn't have to be a whole number. Once you've created the Age column, remove the other date-related columns, including the one you created with Pandas.

In [19]:
songs['Day'] = 1
songs['Date']=pd.to_datetime(songs[['Year','Month','Day']])

songs['Today'] = pd.to_datetime('2022-9-6')

songs['Age']=songs['Today']-songs['Date']
songs.dtypes

Index                               int64
Title                              object
Artist                             object
Top Genre                          object
Year                              float64
Month                              object
Beats Per Minute (BPM)            float64
Energy                            float64
Loudness (dB)                     float64
Liveness                          float64
Length (Duration)                 float64
Acousticness                      float64
Speechiness                       float64
Popularity                        float64
Day                                 int64
Date                       datetime64[ns]
Today                      datetime64[ns]
Age                       timedelta64[ns]
dtype: object

In [20]:
songs=songs.drop(columns=['Year','Month','Day','Date','Today'])
songs.head()

,Index,Title,Artist,Top Genre,Beats Per Minute (BPM),Energy,Loudness (dB),Liveness,Length (Duration),Acousticness,Speechiness,Popularity,Age
0,1,Sunrise,Norah Jones,adult standards,157.0,30.0,-14.0,11.0,201.0,94.0,3.0,71.0,6549 days
1,2,Black Night,Deep Purple,album rock,135.0,79.0,-11.0,17.0,207.0,17.0,7.0,39.0,8224 days
2,3,Clint Eastwood,Gorillaz,alternative hip hop,168.0,69.0,-9.0,7.0,341.0,2.0,17.0,69.0,7767 days
3,4,The Pretender,Foo Fighters,alternative metal,173.0,96.0,-4.0,3.0,269.0,0.0,4.0,76.0,5727 days
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,106.0,82.0,-5.0,10.0,256.0,1.0,3.0,59.0,7341 days

Create dummy variables for the categorical features. Drop one level of each feature to end up with k-1 dummies, not k.

In [21]:
songs_dc = pd.get_dummies(songs, prefix='', prefix_sep='', columns = ['Title','Artist','Top Genre'],drop_first=True)
songs_dc.head()

,Index,Beats Per Minute (BPM),Energy,Loudness (dB),Liveness,Length (Duration),Acousticness,Speechiness,Popularity,Age,...,reggae,reggae fusion,rock-and-roll,scottish singer-songwriter,soft rock,stomp and holler,streektaal,trance,uk pop,yacht rock
0,1,157.0,30.0,-14.0,11.0,201.0,94.0,3.0,71.0,6549 days,...,0,0,0,0,0,0,0,0,0,0
1,2,135.0,79.0,-11.0,17.0,207.0,17.0,7.0,39.0,8224 days,...,0,0,0,0,0,0,0,0,0,0
2,3,168.0,69.0,-9.0,7.0,341.0,2.0,17.0,69.0,7767 days,...,0,0,0,0,0,0,0,0,0,0
3,4,173.0,96.0,-4.0,3.0,269.0,0.0,4.0,76.0,5727 days,...,0,0,0,0,0,0,0,0,0,0
4,5,106.0,82.0,-5.0,10.0,256.0,1.0,3.0,59.0,7341 days,...,0,0,0,0,0,0,0,0,0,0

# Model Training Exercise

Using your processed data set from the previous exercise, create a new Pandas DataFrame called X that includes everything except the target variable column. Make sure this is a new object; don't overwrite any previous data sets.

In [22]:
X = songs_dc.copy()
X = X.drop(columns= 'Popularity')
X

,Index,Beats Per Minute (BPM),Energy,Loudness (dB),Liveness,Length (Duration),Acousticness,Speechiness,Age,(Everything I Do) I Do It For You,...,reggae,reggae fusion,rock-and-roll,scottish singer-songwriter,soft rock,stomp and holler,streektaal,trance,uk pop,yacht rock
0,1,157.0,30.0,-14.0,11.0,201.0,94.0,3.0,6549 days,0,...,0,0,0,0,0,0,0,0,0,0
1,2,135.0,79.0,-11.0,17.0,207.0,17.0,7.0,8224 days,0,...,0,0,0,0,0,0,0,0,0,0
2,3,168.0,69.0,-9.0,7.0,341.0,2.0,17.0,7767 days,0,...,0,0,0,0,0,0,0,0,0,0
3,4,173.0,96.0,-4.0,3.0,269.0,0.0,4.0,5727 days,0,...,0,0,0,0,0,0,0,0,0,0
4,5,106.0,82.0,-5.0,10.0,256.0,1.0,3.0,7341 days,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,1990,94.0,21.0,-12.0,11.0,128.0,84.0,7.0,23534 days,0,...,0,0,0,0,0,0,0,0,0,0
1990,1991,175.0,76.0,-8.0,76.0,136.0,73.0,6.0,23473 days,0,...,0,0,0,0,0,0,0,0,0,0
1991,1992,168.0,80.0,-9.0,31.0,162.0,74.0,7.0,23169 days,0,...,0,0,0,0,0,0,0,0,0,0
1992,1993,174.0,26.0,-13.0,7.0,324.0,54.0,4.0,22986 days,0,...,0,0,0,0,0,0,0,0,0,0
1993,1994,133.0,50.0,-10.0,16.0,148.0,74.0,3.0,23108 days,0,...,0,0,0,0,0,0,0,0,0,0

Create a new Pandas Series called y that includes just the target variable column. Again, make sure this is a new object.

In [23]:
y = songs_dc['Popularity'].copy()
y

0       71.0
1       39.0
2       69.0
3       76.0
4       59.0
        ...
1989    63.0
1990    69.0
1991    74.0
1992    65.0
1993    56.0
Name: Popularity, Length: 1994, dtype: float64

Following the documentation above, create new objects X_train, X_test, y_train, and y_test. Let the test set be 30% of the original data set. Specify a random seed value of your choice so you can reproduce your steps later.

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.33, random_state=42
)

In [25]:
X_train.describe()

,Index,Beats Per Minute (BPM),Energy,Loudness (dB),Liveness,Length (Duration),Acousticness,Speechiness,Age,(Everything I Do) I Do It For You,...,reggae,reggae fusion,rock-and-roll,scottish singer-songwriter,soft rock,stomp and holler,streektaal,trance,uk pop,yacht rock
count,1335.000000,1335.000000,1335.000000,1335.000000,1335.000000,1335.000000,1335.000000,1335.000000,1335,1335.0,...,1335.000000,1335.000000,1335.000000,1335.000000,1335.000000,1335.0,1335.000000,1335.000000,1335.000000,1335.0
mean,995.525843,119.462057,59.602482,-9.012784,19.291454,263.044120,29.544703,5.130314,10766 days 10:26:41.797752704,0.0,...,0.004494,0.002996,0.000749,0.000749,0.000749,0.0,0.000749,0.000749,0.000749,0.0
std,578.653604,28.167869,22.185600,3.672988,17.095762,99.205104,29.432590,4.720313,5953 days 14:26:59.996770048,0.0,...,0.066914,0.054676,0.027369,0.027369,0.027369,0.0,0.027369,0.027369,0.027369,0.0
min,1.000000,15.000000,3.000000,-27.000000,2.000000,93.000000,0.000000,2.000000,1010 days 00:00:00,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
25%,501.500000,99.000000,42.000000,-11.000000,9.000000,210.000000,4.000000,3.000000,5423 days 00:00:00,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
50%,995.000000,119.000000,61.000000,-9.000000,13.000000,246.000000,18.000000,4.000000,10567 days 00:00:00,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
75%,1495.500000,135.000000,77.000000,-6.000000,23.000000,289.500000,51.000000,5.000000,16000 days 00:00:00,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
max,1994.000000,305.000000,100.000000,-2.000000,99.000000,1412.000000,98.000000,55.000000,24142 days 00:00:00,0.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,0.0

In [26]:
X_test.describe()

,Index,Beats Per Minute (BPM),Energy,Loudness (dB),Liveness,Length (Duration),Acousticness,Speechiness,Age,(Everything I Do) I Do It For You,...,reggae,reggae fusion,rock-and-roll,scottish singer-songwriter,soft rock,stomp and holler,streektaal,trance,uk pop,yacht rock
count,659.000000,659.000000,659.000000,659.000000,659.000000,659.000000,659.000000,659.000000,659,659.000000,...,659.000000,659.0,659.0,659.000000,659.0,659.000000,659.0,659.0,659.0,659.000000
mean,1001.499241,121.787907,59.789074,-9.003035,18.449185,261.738411,27.585736,4.705599,10432 days 09:23:45.796661632,0.001517,...,0.003035,0.0,0.0,0.001517,0.0,0.001517,0.0,0.0,0.0,0.001517
std,570.277207,29.301532,21.987689,3.592460,15.885086,80.912823,27.962086,3.647642,5744 days 07:16:37.464859200,0.038954,...,0.055048,0.0,0.0,0.038954,0.0,0.038954,0.0,0.0,0.0,0.038954
min,3.000000,37.000000,5.000000,-22.000000,3.000000,127.000000,0.000000,2.000000,1010 days 00:00:00,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
25%,495.500000,99.500000,43.000000,-11.000000,9.000000,216.000000,3.000000,3.000000,5271 days 00:00:00,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
50%,1002.000000,121.000000,61.000000,-8.000000,12.000000,245.000000,17.000000,4.000000,10475 days 00:00:00,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
75%,1494.500000,138.500000,78.500000,-6.000000,22.000000,289.000000,48.000000,5.000000,14813 days 00:00:00,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
max,1993.000000,198.000000,99.000000,-2.000000,99.000000,1121.000000,99.000000,39.000000,23534 days 00:00:00,1.000000,...,1.000000,0.0,0.0,1.000000,0.0,1.000000,0.0,0.0,0.0,1.000000

In [27]:
y_train.describe()

count    1335.000000
mean       59.567515
std        14.184951
min        12.000000
25%        50.000000
50%        62.000000
75%        71.000000
max       100.000000
Name: Popularity, dtype: float64

In [28]:
y_test.describe()

count    659.000000
mean      59.420334
std       14.651813
min       11.000000
25%       49.000000
50%       61.000000
75%       70.000000
max       98.000000
Name: Popularity, dtype: float64